pipeline {
    agent {
        dockerfile {
            dir 'ci'
        }
    }

    environment {
        MAKEFLAGS = "-j 2"
    }

    stages {
        stage('Release Build') {
            steps {
                sh '''
                    rm -rf release_build && mkdir release_build && cd release_build
                    cmake .. -DENABLE_PYTHON=OFF -DCMAKE_BUILD_TYPE=Release -DBOOST_RANDOM_VERSION=1.58
                    make 
                   ./bin/tests
            '''
            }
        }
        stage('Debug Build') {
            steps {
                sh '''
                    rm -rf debug_build && mkdir debug_build && cd debug_build
                    cmake .. -DENABLE_PYTHON=OFF -DCMAKE_BUILD_TYPE=Debug -DBOOST_RANDOM_VERSION=1.58
                    make 
                   ./bin/tests
            '''
            }
        }
    }
}
